name: CI

on:
  pull_request:
    branches:
      - dev
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Specify the Node.js versions you want to test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint -- --format node_modules/eslint-formatter-github
        continue-on-error: true

      - name: Annotate ESLint output
        if: failure()
        run: |
          echo "ESLint found issues:"
          cat ${GITHUB_WORKSPACE}/eslint.log
        continue-on-error: true
