name: CI

on:
  push:
    branches:
      - main
      - dev
      - dev-sandeep
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev
      - dev-sandeep

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Specify the Node.js versions you want to test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for Next.js
        run: npm install

      - name: Run lint
        run: npm run lint

      # - name: Run SonarQube Scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
      #   # working-directory: ./frontend
      #   run: |
      #     npm install -g sonarqube-scanner
      #     sonar-scanner \
      #       -Dsonar.projectKey=LikithKumarDK_Django-NextJS \
      #       -Dsonar.sources=./ \
      #       -Dsonar.host.url=https://sonarcloud.io \
      #       -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
      #       -Dsonar.login=$SONAR_TOKEN
